### DISCUSSION TITLE
localCA is so good!

### DISCUSSION THREAD

**Discussion by SinisterSpatula** [tgangte/LocalCA#22] [General]
wow this was exactly what I was looking for and I love the simple UI.  Great job on it!  One improvement I'd like to suggest is to add to the readme how to go about adding the created certificate to nginx of the container.  I came up with this solution for mine:

![image](https://github.com/user-attachments/assets/a75b5519-b13f-4124-b89b-fdc77873cf82)

## compose.yaml:
```yml
# github - https://github.com/tgangte/LocalCA
services:
  web:
    image: practicalsre/local-ca:latest
    container_name: localca
    restart: unless-stopped
    volumes:
      - db:/app/db
      - static_volume:/app/staticfiles
    networks:
      - app_network
    command: >
      sh -c "
        ls -l
        python manage.py migrate &&
        python manage.py initadmin &&
        python manage.py collectstatic --noinput &&
        exec gunicorn localca_project.wsgi --bind 0.0.0.0:8000 --worker-class=gthread --threads=4"
  nginx:
    image: practicalsre/local-ca-nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
      - 8001:443
    volumes:
      - static_volume:/app/staticfiles:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./localca.home.arpa_chain.pem:/etc/nginx/certs/localca.home.arpa_chain.pem
      - ./localca.home.arpa_private.pem:/etc/nginx/certs/localca.home.arpa_private.pem
    depends_on:
      - web
    networks:
      app_network: null
      macvlan_network:
        ipv4_address: 192.168.200.67 # Choose an unused IP within your subnet
volumes:
  static_volume: null
  db: null
networks:
  app_network:
    driver: bridge
  macvlan_network:
    external: true
````

## default.conf

```
server {
    listen 443 ssl;
    server_name localca.home.arpa;

    ssl_certificate /etc/nginx/certs/localca.home.arpa_chain.pem;
    ssl_certificate_key /etc/nginx/certs/localca.home.arpa_private.pem;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
    }
}

server {
    listen 80;
    server_name localca.home.arpa;

    # Redirect HTTP to HTTPS
    return 301 https://$host$request_uri;
}
```
